"""create_instagram_tables_fix

Revision ID: 55fc51571caf
Revises: 0cd128b68af7
Create Date: 2025-07-01 01:18:38.392926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fc51571caf'
down_revision = '0cd128b68af7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instagram_user_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_accounts_id'), 'instagram_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_instagram_user_id'), 'instagram_accounts', ['instagram_user_id'], unique=True)
    op.create_index(op.f('ix_instagram_accounts_user_id'), 'instagram_accounts', ['user_id'], unique=False)
    op.create_table('instagram_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instagram_media_id', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_media_account_id'), 'instagram_media', ['account_id'], unique=False)
    op.create_index(op.f('ix_instagram_media_id'), 'instagram_media', ['id'], unique=False)
    op.create_index(op.f('ix_instagram_media_instagram_media_id'), 'instagram_media', ['instagram_media_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_media_instagram_media_id'), table_name='instagram_media')
    op.drop_index(op.f('ix_instagram_media_id'), table_name='instagram_media')
    op.drop_index(op.f('ix_instagram_media_account_id'), table_name='instagram_media')
    op.drop_table('instagram_media')
    op.drop_index(op.f('ix_instagram_accounts_user_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_instagram_user_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_id'), table_name='instagram_accounts')
    op.drop_table('instagram_accounts')
    # ### end Alembic commands ### 