"""add_instagram_tables

Revision ID: 0cd128b68af7
Revises: 7a6df0865437
Create Date: 2025-06-30 23:55:12.437911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd128b68af7'
down_revision = '7a6df0865437'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 